
drop table OPOSICION;
drop table REL_DEP_EPI;
drop table DEPARTAMENTO;
drop table EPIGRAFE;
create table DEPARTAMENTO(
ETQ VARCHAR(1000) not null primary key,
NOMBRE VARCHAR(1000) not null
);

create table EPIGRAFE(
NOMBRE VARCHAR(1000) not null primary key
);

create table REL_DEP_EPI(
NOMBREEP VARCHAR(1000) not null,
ETQDEP VARCHAR(1000) not null,
PRIMARY KEY(NOMBREEP,ETQDEP),
FOREIGN KEY(NOMBREEP) REFERENCES EPIGRAFE(NOMBRE),
FOREIGN KEY(ETQDEP) REFERENCES DEPARTAMENTO(ETQ)
);


create table OPOSICION(
ID VARCHAR(1000) not null primary key,
FECHA DATE not null,
CONTROL VARCHAR(10) not null,
NOMBREEP VARCHAR(1000) not null,
ETQDEP VARCHAR(1000) not null,
URLPDF VARCHAR(200) not null,
URLXML VARCHAR(200) not null,
TITULO VARCHAR(1000) not null,
FOREIGN KEY(NOMBREEP,ETQDEP) REFERENCES REL_DEP_EPI(NOMBREEP,ETQDEP)

);
